name: HeavyStack

services:
  # Jellyfin - Media Server (needs special permissions)
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    user: ${JELLYFIN_PUID:-1000}:${JELLYFIN_PGID:-1000}
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
      - TZ=${JELLYFIN_TIMEZONE:-America/Sao_Paulo}
    volumes:
      - ./configs/jellyfin/etc:/etc/jellyfin
      - ./configs/jellyfin/var-cache:/var/cache/jellyfin
      - ./configs/jellyfin/var-lib:/var/lib/jellyfin
      - ./configs/jellyfin/var-log:/var/log/jellyfin
      - ./configs/jellyfin/timezone:/etc/timezone
      - myMedia:/mnt/media
    group_add:
      - "109"
    network_mode: "host"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped

  # Jellyseerr - Media Requests (needs special permissions)
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    networks:
      - default
    user: ${JELLYFIN_PUID:-1000}:${JELLYFIN_PGID:-1000}
    environment:
      - TZ=${JELLYSEERR_TIMEZONE:-America/Sao_Paulo}
    ports:
      - ${JELLYSEERR_PORT:-5055}:5055
    volumes:
      - ./configs/mediarr/jellyseerr:/app/config
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr

  # Sonarr (for jellyseerr dependency)
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    networks:
      - default
    environment:
      - PUID=${SONARR_PUID:-1000}
      - PGID=${SONARR_PGID:-100}
      - TZ=${SONARR_TZ:-America/Sao_Paulo}
    volumes:
      - ./configs/mediarr/sonarr:/config
      - myMedia:/mnt/media
      - myDlFolders:/mnt/downloads
    depends_on:
      - prowlarr
      - qbittorrent
    ports:
      - 8989:8989
    restart: unless-stopped

  # Radarr (for jellyseerr dependency)
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      - default
    environment:
      - PUID=${RADARR_PUID:-1000}
      - PGID=${RADARR_PGID:-100}
      - TZ=${RADARR_TZ:-America/Sao_Paulo}
    volumes:
      - ./configs/mediarr/radarr:/config
      - myMedia:/mnt/media
      - myDlFolders:/mnt/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent

  # Prowlarr (dependency)
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    networks:
      - default
    environment:
      - PUID=${PROWLARR_PUID:-1000}
      - PGID=${PROWLARR_PGID:-100}
      - TZ=${PROWLARR_TZ:-America/Sao_Paulo}
    volumes:
      - ./configs/mediarr/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on:
      - flaresolverr

  # FlareSolverr (dependency)
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    networks:
      - default
    environment:
      - LOG_LEVEL=${FLARESOLVERR_LOG_LEVEL:-info}
      - LOG_HTML=${FLARESOLVERR_LOG_HTML:-false}
      - CAPTCHA_SOLVER=${FLARESOLVERR_CAPTCHA_SOLVER:-none}
      - TZ=${FLARESOLVERR_TZ:-America/Sao_Paulo}
    restart: unless-stopped

  # qBittorrent (dependency)
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    networks:
      - default
    environment:
      - PUID=${QBITTORRENT_PUID:-1000}
      - PGID=${QBITTORRENT_PGID:-100}
      - TZ=${QBITTORRENT_TZ:-America/Sao_Paulo}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT:-8081}
    volumes:
      - ./configs/mediarr/qbittorrent:/config
      - myDlFolders:/downloads
    ports:
      - ${QBITTORRENT_WEBUI_PORT:-8081}:${QBITTORRENT_WEBUI_PORT:-8081}
      - ${QBITTORRENT_PORT:-6881}:6881
      - ${QBITTORRENT_PORT:-6881}:6881/udp
    restart: unless-stopped

networks:
  default:
    name: heavystack_mediarr
    external: true

volumes:
  myMedia:
    name: heavystack_myMedia
    external: true
  myDlFolders:
    name: heavystack_myDlFolders
    external: true
